//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyBoomService
{
    using System;
    using System.Collections.Generic;
    
    public partial class answer
    {
        public int id { get; set; }
        public int question_id { get; set; }
        public int user_id { get; set; }
        public Nullable<int> option_id { get; set; }
        public string answer_text_field { get; set; }
    
        public virtual option option { get; set; }
        public virtual question question { get; set; }
        public virtual user user { get; set; }
    }
}
