//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyBoomService
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        public question()
        {
            this.answers = new HashSet<answer>();
            this.options = new HashSet<option>();
        }
    
        public int id { get; set; }
        public string question_text { get; set; }
        public int survey_id { get; set; }
        public int input_type_id { get; set; }
    
        public virtual ICollection<answer> answers { get; set; }
        public virtual input_type input_type { get; set; }
        public virtual ICollection<option> options { get; set; }
        public virtual survey survey { get; set; }
    }
}
