//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyBoomService
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.answers = new HashSet<answer>();
            this.surveys = new HashSet<survey>();
        }
    
        public string username { get; set; }
        public string password { get; set; }
        public int id { get; set; }
    
        public virtual ICollection<answer> answers { get; set; }
        public virtual ICollection<survey> surveys { get; set; }
    }
}
