package com.thomas.soap;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.7.0
//
// Created by Quasar Development at 18-06-2015
//
//---------------------------------------------------





public class Enums
{

    public enum QuestionType
    {
        
        MultipleChoice(0),
        
        TrueOrFalse(1),
        
        ShortAnswer(2);
        
        private int code;
        
        QuestionType(int code ){
            this.code = code;
        }
    
        public int getCode(){
		    return code;
	    }
    

        public static QuestionType fromString(String str)
        {
            if (str.equals("MultipleChoice"))
                return MultipleChoice;
            if (str.equals("TrueOrFalse"))
                return TrueOrFalse;
            if (str.equals("ShortAnswer"))
                return ShortAnswer;
		    return null;
        }
    }

}