package com.thomas.soap;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.7.0
//
// Created by Quasar Development at 18-06-2015
//
//---------------------------------------------------



import org.ksoap2.SoapEnvelope;
import org.ksoap2.serialization.*;
import org.kxml2.io.KXmlParser;
import org.kxml2.kdom.Element;
import org.xmlpull.v1.XmlPullParser;
import org.xmlpull.v1.XmlPullParserFactory;
import org.xmlpull.v1.XmlSerializer;

import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Vector;
import java.io.StringReader;
import java.io.StringWriter;

//If you have a compilation error here then you have to add a reference to ExKsoap2-1.0.1.0.jar to your project (you can find it in Libs folder in the generated zip file)
public class ExtendedSoapSerializationEnvelope extends com.easywsdl.exksoap2.serialization.ExSoapSerializationEnvelope {
    static HashMap< String,Class> classNames = new HashMap< String, Class>();
    static {
        classNames.put("http://surveyboomservice.azurewebsites.net/^^SurveyTransport",SurveyTransport.class);
        classNames.put("http://surveyboomservice.azurewebsites.net/^^QuestionTransport",QuestionTransport.class);
        classNames.put("http://surveyboomservice.azurewebsites.net/^^GetUserID",GetUserID.class);
        classNames.put("http://surveyboomservice.azurewebsites.net/^^GetUserIDResponse",GetUserIDResponse.class);
        classNames.put("http://surveyboomservice.azurewebsites.net/^^UserLogin",UserLogin.class);
        classNames.put("http://surveyboomservice.azurewebsites.net/^^UserLoginResponse",UserLoginResponse.class);
        classNames.put("http://surveyboomservice.azurewebsites.net/^^HasAccount",HasAccount.class);
        classNames.put("http://surveyboomservice.azurewebsites.net/^^HasAccountResponse",HasAccountResponse.class);
        classNames.put("http://surveyboomservice.azurewebsites.net/^^ChangePassword",ChangePassword.class);
        classNames.put("http://surveyboomservice.azurewebsites.net/^^ChangePasswordResponse",ChangePasswordResponse.class);
        classNames.put("http://surveyboomservice.azurewebsites.net/^^CreateUser",CreateUser.class);
        classNames.put("http://surveyboomservice.azurewebsites.net/^^CreateUserResponse",CreateUserResponse.class);
        classNames.put("http://surveyboomservice.azurewebsites.net/^^CreateSurvey",CreateSurvey.class);
        classNames.put("http://surveyboomservice.azurewebsites.net/^^CreateSurveyResponse",CreateSurveyResponse.class);
        classNames.put("http://surveyboomservice.azurewebsites.net/^^GetSurvey",GetSurvey.class);
        classNames.put("http://surveyboomservice.azurewebsites.net/^^GetSurveyResponse",GetSurveyResponse.class);
        classNames.put("http://surveyboomservice.azurewebsites.net/^^SubmitSurveyResponse",SubmitSurveyResponse.class);
        classNames.put("http://surveyboomservice.azurewebsites.net/^^SubmitSurveyResponseResponse",SubmitSurveyResponseResponse.class);
        classNames.put("http://surveyboomservice.azurewebsites.net/^^GetAllResponses",GetAllResponses.class);
        classNames.put("http://surveyboomservice.azurewebsites.net/^^GetAllResponsesResponse",GetAllResponsesResponse.class);
        classNames.put("http://surveyboomservice.azurewebsites.net/^^GetSurveysByUserID",GetSurveysByUserID.class);
        classNames.put("http://surveyboomservice.azurewebsites.net/^^GetSurveysByUserIDResponse",GetSurveysByUserIDResponse.class);
        classNames.put("http://surveyboomservice.azurewebsites.net/^^GetAllSurveys",GetAllSurveys.class);
        classNames.put("http://surveyboomservice.azurewebsites.net/^^GetAllSurveysResponse",GetAllSurveysResponse.class);
        classNames.put("http://surveyboomservice.azurewebsites.net/^^ArrayOfQuestionTransport",ArrayOfQuestionTransport.class);
        classNames.put("http://surveyboomservice.azurewebsites.net/^^ArrayOfString",ArrayOfString.class);
        classNames.put("http://surveyboomservice.azurewebsites.net/^^ArrayOfSurveyTransport",ArrayOfSurveyTransport.class);
    }   

    protected static final int QNAME_NAMESPACE = 0;
    private static final String TYPE_LABEL = "type";

    public ExtendedSoapSerializationEnvelope() {
        this(SoapEnvelope.VER11);
    }

    public ExtendedSoapSerializationEnvelope(int soapVersion) {
        super(soapVersion);
        implicitTypes = true;
        setAddAdornments(false);
        new MarshalGuid().register(this);
        new MarshalFloat().register(this);
    }

    

    @Override
    protected void writeProperty(XmlSerializer writer, Object obj, PropertyInfo type) throws IOException {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if (obj == null || obj== SoapPrimitive.NullNilElement) {
            writer.attribute(xsi, version >= VER12 ? NIL_LABEL : NULL_LABEL, "true");
            return;
        }
        if(writeReferenceObject(writer,obj))
        {
            return;
        }
        Object[] qName = getInfo(null, obj);
        if (!type.multiRef && qName[2] == null )
        {
            
            if (!implicitTypes || (obj.getClass() != type.type && !(obj instanceof Vector ) && type.type!=String.class)) {
                String xmlName=Helper.getKeyByValue(classNames,obj.getClass());
                if(xmlName!=null) {
                    String[] parts = xmlName.split("\\^\\^");
                    String prefix = writer.getPrefix(parts[0], true);
                    writer.attribute(xsi, TYPE_LABEL, prefix + ":" + parts[1]);
                }
                else
                {
                    if(type.type instanceof String) {
                        String xsdPrefix = writer.getPrefix(xsd, true);
                        String myType = (String) type.type;
                        String[] parts = myType.split("\\^\\^");
                        if (parts.length == 2) {
                            xsdPrefix = writer.getPrefix(parts[0], true);
                            myType = parts[1];
                        }

                        writer.attribute(xsi, TYPE_LABEL, xsdPrefix + ":" + myType);
                    }
                    else
                    {
                        String prefix = writer.getPrefix(type.namespace, true);
                        writer.attribute(xsi, TYPE_LABEL, prefix + ":" + obj.getClass().getSimpleName());
                    }

                }
            }
            //super.writeProperty(writer,obj,type);

            //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
            //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
            writeElement(writer, obj, type, qName[QNAME_MARSHAL]);
        }
        else {
            super.writeProperty(writer, obj, type);
        }
    }

    public SoapObject GetExceptionDetail(Element detailElement,String exceptionElementNS,String exceptionElementName)
    {
        int index=detailElement.indexOf(exceptionElementNS,exceptionElementName,0);
        if(index>-1)
        {
            Element errorElement=detailElement.getElement(index);
            return GetSoapObject(errorElement);
        }
        return null;
    }

    public SoapObject GetSoapObject(Element detailElement) {
        try{
            XmlSerializer xmlSerializer = XmlPullParserFactory.newInstance().newSerializer();
            StringWriter writer = new StringWriter();
            xmlSerializer.setOutput(writer);
            detailElement.write(xmlSerializer);
            xmlSerializer.flush();

            XmlPullParser xpp = new KXmlParser();
            xpp.setFeature(XmlPullParser.FEATURE_PROCESS_NAMESPACES, true);

            xpp.setInput(new StringReader(writer.toString()));
            xpp.nextTag();
            SoapObject soapObj = new SoapObject(detailElement.getNamespace(),detailElement.getName());
            readSerializable(xpp,soapObj);
            return soapObj;
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
        }
        return null;
    }

    public Object GetHeader(Element detailElement) {
        if(detailElement.getText(0)!=null)
        {
            SoapPrimitive primitive = new SoapPrimitive(detailElement.getNamespace(),detailElement.getName(),detailElement.getText(0));
            return  primitive;
        }
    
        return GetSoapObject(detailElement);
    }
    
    public Object get(Object soap,Class cl)
    {
        if(soap==null)
        {
            return null;
        }
        try
        {
            if(soap instanceof  Vector)
            {
                Constructor ctor = cl.getConstructor(Object.class,ExtendedSoapSerializationEnvelope.class);
                return ctor.newInstance(soap,this);
            }
            Object refAttr=getReference(soap);
            if (refAttr != null)
            {
                return refAttr;
            }
            else
            {
                if(soap instanceof SoapObject)
                {
                    String key=String.format("%s^^%s",((SoapObject)soap).getNamespace(),((SoapObject)soap).getName());
                    if(classNames.containsKey(key))
                    {
                        cl=classNames.get(key);
                    }
                }
                Constructor ctor = cl.getConstructor(Object.class,ExtendedSoapSerializationEnvelope.class);
                return ctor.newInstance(soap,this);
            }
        }
        catch (Exception ex)
        {
            ex.printStackTrace();
            return null;
        }
    }

    public Object getSpecificType(Object obj)
    {
        if(obj==null)
        {
            return null;
        }
        if(obj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)obj;
            String key=soapObject.getNamespace()+"^^"+soapObject.getName();
            if(classNames.containsKey(key))
            {
                Class cl=classNames.get(key);
                try
                {
                    Constructor ctor  = cl.getConstructor(Object.class,ExtendedSoapSerializationEnvelope.class);
                    return ctor.newInstance(soapObject,this);
                } 
                catch (Exception e)
                {
                    e.printStackTrace();
                }
            }
        }

        return obj;
    }

    public static Object getXSDType(Object param)
    {
        if(param==null)
        {
            return null;
        }
        Class obj=param.getClass();
        if(obj.equals(String.class))
        {
            return "string";
        }
        if(obj.equals(int.class) || obj.equals(Integer.class))
        {
            return "int";
        }
        if(obj.equals(float.class) || obj.equals(Float.class))
        {
            return "float";
        }
        if(obj.equals(double.class) || obj.equals(Double.class))
        {
            return "double";
        }
        if(obj.equals(java.math.BigDecimal.class))
        {
            return "decimal";
        }
        if(obj.equals(short.class) || obj.equals(Short.class))
        {
            return "short";
        }
        if(obj.equals(long.class) || obj.equals(Long.class))
        {
            return "long";
        }
        if(obj.equals(boolean.class) || obj.equals(Boolean.class))
        {
            return "boolean";
        }
        String xmlName=Helper.getKeyByValue(classNames,obj);
        if(xmlName==null)
        {
            return obj;
        }
        return xmlName;
    }
} 

