package com.thomas.soap;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.7.0
//
// Created by Quasar Development at 18-06-2015
//
//---------------------------------------------------



public interface IServiceEvents
{
    public void Starting();
    public void Completed(OperationResult result);
}
