package com.thomas.soap;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.7.0
//
// Created by Quasar Development at 18-06-2015
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class QuestionTransport extends AttributeContainer implements KvmSerializable,java.io.Serializable
{
    
    public Enums.QuestionType Type=Enums.QuestionType.MultipleChoice;
    
    public String QuestionText;
    
    public ArrayOfString Options=new ArrayOfString();
    
    public String ResponseString;

    public QuestionTransport ()
    {
    }

    public QuestionTransport (Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("Type"))
        {	
	        Object obj = soapObject.getProperty("Type");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.Type = Enums.QuestionType.fromString(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Enums.QuestionType){
                this.Type = (Enums.QuestionType)obj;
            }    
        }
        if (soapObject.hasProperty("QuestionText"))
        {	
	        Object obj = soapObject.getProperty("QuestionText");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.QuestionText = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.QuestionText = (String)obj;
            }    
        }
        if (soapObject.hasProperty("Options"))
        {	
	        Object j = soapObject.getProperty("Options");
	        this.Options = new ArrayOfString(j,__envelope);
        }
        if (soapObject.hasProperty("ResponseString"))
        {	
	        Object obj = soapObject.getProperty("ResponseString");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.ResponseString = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.ResponseString = (String)obj;
            }    
        }


    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Type!=null?this.Type.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.QuestionText!=null?this.QuestionText:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.Options!=null?this.Options:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.ResponseString!=null?this.ResponseString:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Type";
            info.namespace= "http://surveyboomservice.azurewebsites.net/";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "QuestionText";
            info.namespace= "http://surveyboomservice.azurewebsites.net/";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "Options";
            info.namespace= "http://surveyboomservice.azurewebsites.net/";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ResponseString";
            info.namespace= "http://surveyboomservice.azurewebsites.net/";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }
}
