package com.thomas.soap;




//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.7.0
//
// Created by Quasar Development at 18-06-2015
//
//---------------------------------------------------




import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.*;
import org.ksoap2.transport.*;
import org.kxml2.kdom.Element;

import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class SurveyBoomServiceSoap12
{
    interface IWcfMethod
    {
        ExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws Exception;

        Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope, Object result) throws Exception;
    }

    String url="http://surveyboomservice.azurewebsites.net/SurveyBoomService.asmx";

    int timeOut=60000;
    public List< HeaderProperty> httpHeaders;
    public boolean enableLogging;

    IServiceEvents callback;
    public SurveyBoomServiceSoap12(){}

    public SurveyBoomServiceSoap12 (IServiceEvents callback)
    {
        this.callback = callback;
    }
    public SurveyBoomServiceSoap12(IServiceEvents callback,String url)
    {
        this.callback = callback;
        this.url = url;
    }

    public SurveyBoomServiceSoap12(IServiceEvents callback,String url,int timeOut)
    {
        this.callback = callback;
        this.url = url;
        this.timeOut=timeOut;
    }

    protected Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                return new com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            }
            else
            {
                return new com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }
    
    protected ExtendedSoapSerializationEnvelope createEnvelope()
    {
        ExtendedSoapSerializationEnvelope envelope= new ExtendedSoapSerializationEnvelope(ExtendedSoapSerializationEnvelope.VER12);
        return envelope;
    }
    
    protected List sendRequest(String methodName,ExtendedSoapSerializationEnvelope envelope,Transport transport ,com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile )throws Exception
    {
        if(transport instanceof com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE )
        {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpTransportSE)transport).call(methodName, envelope,httpHeaders,null,profile);
        }
        else
        {
            return ((com.easywsdl.exksoap2.transport.AdvancedHttpsTransportSE)transport).call(methodName, envelope,httpHeaders,null,profile);
        }  
    }

    Object getResult(Class destObj,Object source,String resultName,ExtendedSoapSerializationEnvelope __envelope) throws Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                Object instance=__envelope.get(source,destObj);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                Object instance=__envelope.get(j,destObj);
                return instance;
            }
            else if( soap.getName().equals(resultName)) {
                Object instance=__envelope.get(source,destObj);
                return instance;
            }
       }

       return null;
    }

        
    public Integer GetUserID(final String username ) throws Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (Integer)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://surveyboomservice.azurewebsites.net/", "GetUserID");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://surveyboomservice.azurewebsites.net/";
                __info.name="username";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(username!=null?username:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("GetUserIDResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return Integer.parseInt(j.toString());
                }
                else if (obj!= null && obj instanceof Integer){
                    return (Integer)obj;
                }
                return null;
            }
        },"http://surveyboomservice.azurewebsites.net/GetUserID",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< Integer>> GetUserIDAsync(final String username)
    {
        return executeAsync(new Functions.IFunc< Integer>() {
            public Integer Func() throws Exception {
                return GetUserID( username);
            }
        });
    }
    
    public Boolean UserLogin(final String username,final String password ) throws Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (Boolean)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://surveyboomservice.azurewebsites.net/", "UserLogin");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://surveyboomservice.azurewebsites.net/";
                __info.name="username";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(username!=null?username:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://surveyboomservice.azurewebsites.net/";
                __info.name="password";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(password!=null?password:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("UserLoginResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Boolean(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"http://surveyboomservice.azurewebsites.net/UserLogin",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< Boolean>> UserLoginAsync(final String username,final String password)
    {
        return executeAsync(new Functions.IFunc< Boolean>() {
            public Boolean Func() throws Exception {
                return UserLogin( username,password);
            }
        });
    }
    
    public Boolean HasAccount(final Integer id ) throws Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (Boolean)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://surveyboomservice.azurewebsites.net/", "HasAccount");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://surveyboomservice.azurewebsites.net/";
                __info.name="id";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(id);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("HasAccountResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Boolean(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"http://surveyboomservice.azurewebsites.net/HasAccount",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< Boolean>> HasAccountAsync(final Integer id)
    {
        return executeAsync(new Functions.IFunc< Boolean>() {
            public Boolean Func() throws Exception {
                return HasAccount( id);
            }
        });
    }
    
    public Boolean ChangePassword(final String username,final String oldPassword,final String newPassword ) throws Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (Boolean)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://surveyboomservice.azurewebsites.net/", "ChangePassword");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://surveyboomservice.azurewebsites.net/";
                __info.name="username";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(username!=null?username:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://surveyboomservice.azurewebsites.net/";
                __info.name="oldPassword";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(oldPassword!=null?oldPassword:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://surveyboomservice.azurewebsites.net/";
                __info.name="newPassword";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(newPassword!=null?newPassword:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("ChangePasswordResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Boolean(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"http://surveyboomservice.azurewebsites.net/ChangePassword",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< Boolean>> ChangePasswordAsync(final String username,final String oldPassword,final String newPassword)
    {
        return executeAsync(new Functions.IFunc< Boolean>() {
            public Boolean Func() throws Exception {
                return ChangePassword( username,oldPassword,newPassword);
            }
        });
    }
    
    public Boolean CreateUser(final String username,final String password ) throws Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (Boolean)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://surveyboomservice.azurewebsites.net/", "CreateUser");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://surveyboomservice.azurewebsites.net/";
                __info.name="username";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(username!=null?username:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://surveyboomservice.azurewebsites.net/";
                __info.name="password";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(password!=null?password:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("CreateUserResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Boolean(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"http://surveyboomservice.azurewebsites.net/CreateUser",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< Boolean>> CreateUserAsync(final String username,final String password)
    {
        return executeAsync(new Functions.IFunc< Boolean>() {
            public Boolean Func() throws Exception {
                return CreateUser( username,password);
            }
        });
    }
    
    public Integer CreateSurvey(final SurveyTransport submittedSurvey ) throws Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (Integer)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://surveyboomservice.azurewebsites.net/","submittedSurvey",new SurveyTransport().getClass());
                SoapObject __soapReq = new SoapObject("http://surveyboomservice.azurewebsites.net/", "CreateSurvey");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://surveyboomservice.azurewebsites.net/";
                __info.name="submittedSurvey";
                __info.type=SurveyTransport.class;
                __info.setValue(submittedSurvey!=null?submittedSurvey:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("CreateSurveyResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return Integer.parseInt(j.toString());
                }
                else if (obj!= null && obj instanceof Integer){
                    return (Integer)obj;
                }
                return null;
            }
        },"http://surveyboomservice.azurewebsites.net/CreateSurvey",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< Integer>> CreateSurveyAsync(final SurveyTransport submittedSurvey)
    {
        return executeAsync(new Functions.IFunc< Integer>() {
            public Integer Func() throws Exception {
                return CreateSurvey( submittedSurvey);
            }
        });
    }
    
    public SurveyTransport GetSurvey(final Integer key ) throws Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (SurveyTransport)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://surveyboomservice.azurewebsites.net/", "GetSurvey");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://surveyboomservice.azurewebsites.net/";
                __info.name="key";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(key);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (SurveyTransport)getResult(SurveyTransport.class,__result,"GetSurveyResult",__envelope);
            }
        },"http://surveyboomservice.azurewebsites.net/GetSurvey",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< SurveyTransport>> GetSurveyAsync(final Integer key)
    {
        return executeAsync(new Functions.IFunc< SurveyTransport>() {
            public SurveyTransport Func() throws Exception {
                return GetSurvey( key);
            }
        });
    }
    
    public Boolean SubmitSurveyResponse(final SurveyTransport st,final Integer survey_id ) throws Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (Boolean)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://surveyboomservice.azurewebsites.net/","st",new SurveyTransport().getClass());
                SoapObject __soapReq = new SoapObject("http://surveyboomservice.azurewebsites.net/", "SubmitSurveyResponse");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://surveyboomservice.azurewebsites.net/";
                __info.name="st";
                __info.type=SurveyTransport.class;
                __info.setValue(st!=null?st:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://surveyboomservice.azurewebsites.net/";
                __info.name="survey_id";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(survey_id);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                SoapObject __soap=(SoapObject)__result;
                Object obj = __soap.getProperty("SubmitSurveyResponseResult");
                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    return new Boolean(j.toString());
                }
                else if (obj!= null && obj instanceof Boolean){
                    return (Boolean)obj;
                }
                return null;
            }
        },"http://surveyboomservice.azurewebsites.net/SubmitSurveyResponse",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< Boolean>> SubmitSurveyResponseAsync(final SurveyTransport st,final Integer survey_id)
    {
        return executeAsync(new Functions.IFunc< Boolean>() {
            public Boolean Func() throws Exception {
                return SubmitSurveyResponse( st,survey_id);
            }
        });
    }
    
    public ArrayOfQuestionTransport GetAllResponses(final Integer survey_id ) throws Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (ArrayOfQuestionTransport)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://surveyboomservice.azurewebsites.net/", "GetAllResponses");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://surveyboomservice.azurewebsites.net/";
                __info.name="survey_id";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(survey_id);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (ArrayOfQuestionTransport)getResult(ArrayOfQuestionTransport.class,__result,"GetAllResponsesResult",__envelope);
            }
        },"http://surveyboomservice.azurewebsites.net/GetAllResponses",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< ArrayOfQuestionTransport>> GetAllResponsesAsync(final Integer survey_id)
    {
        return executeAsync(new Functions.IFunc< ArrayOfQuestionTransport>() {
            public ArrayOfQuestionTransport Func() throws Exception {
                return GetAllResponses( survey_id);
            }
        });
    }
    
    public ArrayOfSurveyTransport GetSurveysByUserID(final Integer user_id ) throws Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (ArrayOfSurveyTransport)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://surveyboomservice.azurewebsites.net/", "GetSurveysByUserID");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://surveyboomservice.azurewebsites.net/";
                __info.name="user_id";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(user_id);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (ArrayOfSurveyTransport)getResult(ArrayOfSurveyTransport.class,__result,"GetSurveysByUserIDResult",__envelope);
            }
        },"http://surveyboomservice.azurewebsites.net/GetSurveysByUserID",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< ArrayOfSurveyTransport>> GetSurveysByUserIDAsync(final Integer user_id)
    {
        return executeAsync(new Functions.IFunc< ArrayOfSurveyTransport>() {
            public ArrayOfSurveyTransport Func() throws Exception {
                return GetSurveysByUserID( user_id);
            }
        });
    }
    
    public ArrayOfSurveyTransport GetAllSurveys( ) throws Exception
    {
        com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile __profile = new com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile();
        return (ArrayOfSurveyTransport)execute(new IWcfMethod()
        {
            @Override
            public ExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              ExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://surveyboomservice.azurewebsites.net/", "GetAllSurveys");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                return __envelope;
            }
            
            @Override
            public Object ProcessResult(ExtendedSoapSerializationEnvelope __envelope,Object __result)throws Exception {
                return (ArrayOfSurveyTransport)getResult(ArrayOfSurveyTransport.class,__result,"GetAllSurveysResult",__envelope);
            }
        },"http://surveyboomservice.azurewebsites.net/GetAllSurveys",__profile);
    }
    
    public android.os.AsyncTask< Void, Void, OperationResult< ArrayOfSurveyTransport>> GetAllSurveysAsync()
    {
        return executeAsync(new Functions.IFunc< ArrayOfSurveyTransport>() {
            public ArrayOfSurveyTransport Func() throws Exception {
                return GetAllSurveys( );
            }
        });
    }

    
    protected Object execute(IWcfMethod wcfMethod,String methodName,com.easywsdl.exksoap2.ws_specifications.profile.WS_Profile profile) throws Exception
    {
        Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        ExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport,profile);
            
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);
                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }
    
    protected < T> android.os.AsyncTask< Void, Void, OperationResult< T>>  executeAsync(final Functions.IFunc< T> func)
    {
        return new android.os.AsyncTask< Void, Void, OperationResult< T>>()
        {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            };
            @Override
            protected OperationResult< T> doInBackground(Void... params) {
                OperationResult< T> result = new OperationResult< T>();
                try
                {
                    result.Result= func.Func();
                }
                catch(Exception ex)
                {
                    ex.printStackTrace();
                    result.Exception=ex;
                }
                return result;
            }
            
            @Override
            protected void onPostExecute(OperationResult< T> result)
            {
                callback.Completed(result);
            }
        }.execute();
    }
        
    Exception convertToException(org.ksoap2.SoapFault fault,ExtendedSoapSerializationEnvelope envelope)
    {

        return new Exception(fault.faultstring);
    }
}


