package com.thomas.soap;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.1.7.0
//
// Created by Quasar Development at 18-06-2015
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class SurveyTransport extends AttributeContainer implements KvmSerializable,java.io.Serializable
{
    
    public String Title;
    
    public Integer UserID=0;
    
    public String Description;
    
    public ArrayOfQuestionTransport Questions=new ArrayOfQuestionTransport();
    
    public Integer SurveyID=0;

    public SurveyTransport ()
    {
    }

    public SurveyTransport (Object paramObj,ExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("Title"))
        {	
	        Object obj = soapObject.getProperty("Title");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.Title = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.Title = (String)obj;
            }    
        }
        if (soapObject.hasProperty("UserID"))
        {	
	        Object obj = soapObject.getProperty("UserID");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.UserID = Integer.parseInt(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Integer){
                this.UserID = (Integer)obj;
            }    
        }
        if (soapObject.hasProperty("Description"))
        {	
	        Object obj = soapObject.getProperty("Description");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.Description = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.Description = (String)obj;
            }    
        }
        if (soapObject.hasProperty("Questions"))
        {	
	        Object j = soapObject.getProperty("Questions");
	        this.Questions = new ArrayOfQuestionTransport(j,__envelope);
        }
        if (soapObject.hasProperty("SurveyID"))
        {	
	        Object obj = soapObject.getProperty("SurveyID");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.SurveyID = Integer.parseInt(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Integer){
                this.SurveyID = (Integer)obj;
            }    
        }


    }

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Title!=null?this.Title:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return UserID;
        }
        if(propertyIndex==2)
        {
            return this.Description!=null?this.Description:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.Questions!=null?this.Questions:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return SurveyID;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 5;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Title";
            info.namespace= "http://surveyboomservice.azurewebsites.net/";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "UserID";
            info.namespace= "http://surveyboomservice.azurewebsites.net/";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Description";
            info.namespace= "http://surveyboomservice.azurewebsites.net/";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "Questions";
            info.namespace= "http://surveyboomservice.azurewebsites.net/";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "SurveyID";
            info.namespace= "http://surveyboomservice.azurewebsites.net/";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }

    @Override
    public String getInnerText() {
        return null;
    }

    @Override
    public void setInnerText(String s) {

    }
}
