//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyBoomService
{
    using System;
    using System.Collections.Generic;
    
    public partial class option
    {
        public option()
        {
            this.answers = new HashSet<answer>();
        }
    
        public int id { get; set; }
        public string text { get; set; }
        public int question_id { get; set; }
    
        public virtual ICollection<answer> answers { get; set; }
        public virtual question question { get; set; }
    }
}
