//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyBoomService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SurveyBoomEntities : DbContext
    {
        public SurveyBoomEntities()
            : base("name=SurveyBoomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<answer> answers { get; set; }
        public DbSet<input_type> input_type { get; set; }
        public DbSet<option> options { get; set; }
        public DbSet<question> questions { get; set; }
        public DbSet<survey> surveys { get; set; }
        public DbSet<user> users { get; set; }
    }
}
